[package]
name = "stele"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
datadog-protos = { workspace = true }
ddsketch = { workspace = true, features = ["serde"] }
float-cmp = { workspace = true, features = ["ratio"] }
ordered-float = { workspace = true }
protobuf = { workspace = true }
saluki-common = { workspace = true }
saluki-error = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
stringtheory = { workspace = true }
